#!/usr/bin/env python
# coding: utf-8

# In[3]:


my_dict={'key1':'value1','key2':'value2'}#thier syntax


# In[4]:


my_dict


# In[5]:


my_dict['key1']


# In[6]:


#example


# In[13]:


prices_lookup={'apple':2.54,'oranges':7.76,'milk':4.32}


# In[14]:


prices_lookup['apple']


# In[19]:


d={'k1':123,'k2':[0,2,3],'k3':{'inside key':100}}


# In[20]:


d['k2']


# In[21]:


#if we want to operate the innner value


# In[22]:


d['k3']['inside key']


# In[24]:


d['k2'][2]#here 2 indicates the the index 2


# In[25]:


d={'key1':['a','b','c']}


# In[26]:


d


# In[29]:


mylist=d['key1']


# In[30]:


mylist


# In[31]:


letter=mylist[2]


# In[32]:


letter


# In[33]:


letter.upper()


# In[34]:


#instead of the whole step just do this instead


# In[35]:


d['key1'][2].upper()


# In[36]:


#to add new values in the dictionary


# In[37]:


d={'k1':100,'k2':200}


# In[38]:


d


# In[39]:


d['k3']=300


# In[40]:


d


# In[41]:


#overwrite an existing pair


# In[42]:


d['k2']=200


# In[43]:


d


# In[44]:


d['k2']=3849


# In[45]:


d


# In[46]:


#to only see the keys


# In[47]:


d.keys()


# In[48]:


#to see only the values


# In[49]:


d.values()


# In[50]:


#to see only the pairs


# In[51]:


d.items()


# In[ ]:




