#!/usr/bin/env python
# coding: utf-8

# In[3]:


get_ipython().run_cell_magic('writefile', 'myfile.txt', 'Hello this is a text file\nthis is a second file\nthis is a third file')


# In[4]:


myfile=open('myfile.txt')


# In[5]:


myfile=open('hsuhfd.txt')


# In[6]:


pwd #to check the path of the following file


# In[8]:


myfile=open('myfile.txt')


# In[9]:


myfile.read()


# In[10]:


myfile.read()


# In[11]:


#this is beacuse when we run the curser runs feom the starting till the end so again when we run it comes to the end


# In[12]:


#to set the curser the starting index


# In[14]:


myfile.seek(0)


# In[15]:


myfile.read()


# In[18]:


#to get each line in a seperate list we use readline() function


# In[19]:


myfile.seek(0)


# In[20]:


myfile.readlines()


# In[21]:


#file locations 


# In[22]:


pwd


# In[23]:


#since the file is open now we need to close


# In[24]:


myfile.close()


# In[26]:


with open('myfile.txt') as my_new_file:
    contents=my_new_file.read()


# In[27]:


contents


# In[29]:


with open('myfile.txt',mode='r') as myfile:
    contents=myfile.read()


# In[30]:


contents


# mode='r' is for read only
# mode='a' is to append only(will adds on to files)
# mode='w' is write only (will overwrite files or creates a new files
# mode='r+' is reading and writting
# mode='w+' is writting ans reading (overwrite existing file or creates a new file')

# In[31]:


get_ipython().run_cell_magic('writefile', 'my_new_file.txt', 'one to first\ntwo to second\nthree to third')


# In[32]:


with open('my_new_file.txt',mode='r')as f:
    print(f.read())


# In[33]:


with open('my_new_file.txt',mode='a')as f:
    f.write('four to fourth')


# In[35]:


with open('my_new_file.txt',mode='r')as f:
    print(f.read())


# In[ ]:




