#!/usr/bin/env python
# coding: utf-8

# In[3]:


def lesser_of_two_evens(a,b):
    less=a
    if a>b:
        less=b
    else:
        pass
    return less


# In[4]:


# Check
lesser_of_two_evens(2,4)


# In[5]:


# Check
lesser_of_two_evens(2,5)


# In[6]:


#animal cracker
#ANIMAL CRACKERS: Write a function takes a two-word string and returns True if both words begin with same letter
#animal_crackers('Levelheaded Llama') --> True
#animal_crackers('Crazy Kangaroo') --> False


# In[12]:


def makes_twenty(n1,n2):
    if n1+n2==20:
        print('True')
    else:
        print('False')
    


# In[13]:


# Check
makes_twenty(20,10)


# In[14]:


makes_twenty(2,3)


# In[15]:


#level 1 problem


# In[18]:


def old_macdonald(name):
    if len(name)>4:
        for name[1,4].upper() in name:
    else:
        pass
return name


# In[19]:


def print_big(letter):
    patterns = {1:'  *  ',2:' * * ',3:'*   *',4:'*****',5:'**** ',6:'   * ',7:' *   ',8:'*   * ',9:'*    '}
    alphabet = {'A':[1,2,4,3,3],'B':[5,3,5,3,5],'C':[4,9,9,9,4],'D':[5,3,3,3,5],'E':[4,9,4,9,4]}
    for pattern in alphabet[letter.upper()]:
        print(patterns[pattern])


# In[23]:


print_big('e')


# In[ ]:




