#!/usr/bin/env python
# coding: utf-8

# In[1]:


#sytax of if,elif,and else
#if some_condition:
    #execute some code
#else:
    #execute some code


# In[2]:


#if some_condition:
    #code
#elif somecondition:
    #code
#else:
    #code


# In[3]:


#examples
if True:
    print('its true')


# In[4]:


hungry=True
if hungry:
    print('feed me')
    


# In[5]:


hungry=False
if hungry:
    print('feed me')
else:
    print('im not hungry')


# In[6]:


loc='Bank'
if loc=='Auto shop':
    print('cars are cool')
else:
    print("I do not know")


# In[8]:


loc='Bank'
if loc=='Auto shop':
    print('cars are cool')
elif loc=='Bank':
    print("money is coool")
else:
    print("I do not know")


# In[9]:


loc='Bank'
if loc=='Auto shop':
    print('cars are cool')
elif loc=='Bank':
    print("money is coool")
elif loc=='store':
    print("welocome to store")
else:
    print("I do not know")


# In[10]:


name='sammay'
if name=='frankie':
    print('hello frankie')
elif name=='sammay':
    print("hello sammay")


# FOR LOOPS SYNTAX

# In[11]:


#for example 
my_items=[1,2,3]
for item_name in my_items:
    print(item_name)


# In[13]:


mylist=[1,34,45,7677,523,5,6,67,7]
for mynum in mylist:
    print(mynum)


# In[14]:


for jellu in mylist:
    print('hello')


# In[15]:


#to print only the even numbers
for num in mylist:
    if num%2==0:
        print(num)
    else:
        print('odd number:{num}')


# In[19]:


list_sum=0
for num in mylist:
    list_sum=list_sum+num
    print(list_sum)


# In[20]:


list_sum=0
for num in mylist:
    list_sum=list_sum+num
print(list_sum)


# In[21]:


mystring ='hello world'
for letter in mystring:
    print(letter)


# In[22]:


tup=(1,2,3)
for item in tup:
    print(item)


# In[23]:


mylist=[(1,2),(3,4),(4,5),(6,7)]


# In[25]:


len(mylist)


# In[26]:


for item in mylist:
    print(item)


# In[27]:


#tuple unpacking 


# In[28]:


for a,b in mylist:
    print(a)


# In[29]:


mylist=[(1,2,3),(4,45,5),(5,6,7)]


# In[30]:


for a,b,c in mylist:
    print(c)


# In[31]:


#dicitonary


# In[32]:


d={'k1':1,'k2':2,'k3':3}


# In[33]:


for item in d:
    print(item)


# In[34]:


#the values along the key


# In[40]:


for key,value in d:
    print(value)


# WHILE LOOP

# In[41]:


while some_boolean_condition :
    #do something 
else:
    #do soomething diff
    


# In[45]:


x=0
while x<5:
    print(f'the current value of x is {x}')
    x=x+1


# In[48]:


x=0
while x<5:
    print(f'the current value of x is {x}')
    x+=1
else:
    print("X is not less than 5")


# In[ ]:




