#!/usr/bin/env python
# coding: utf-8

# keywords
# 

# 3 keywords

# break continue pass 

# pass example 
# 

# In[3]:


x=[1,2,3]
for item in x:
    #coomment 


# In[4]:


#to not let the error happen we use the pass comment 


# In[5]:


x=[1,2,3]
for item in x:
    #comment
    pass
    


# continue keyword

# In[6]:


mystring='sammy'
for letter in mystring:
    if letter =='a':
        continue 
    print(letter)


# break
# 

# In[8]:


for letter in mystring:
   if letter=='a':
    break
   print(letter)


# In[9]:


x=0
while x<5:
    if (x==2):
        break
    print(x)
    x+=1


# In[ ]:




