#!/usr/bin/env python
# coding: utf-8

# In[1]:


my_list=[1,2,3]#defination of the list


# In[2]:


my_list=['sukhmani','34','23.2']#it can be a number or a string or a float


# In[3]:


#to check the lenght of the string 


# In[4]:


len(my_list)


# In[5]:


#like string it follows indexing


# In[6]:


my_list=['one','two','three']


# In[7]:


my_list[0]


# In[8]:


my_list[1:]


# concatination

# In[9]:


another_list=['four','five']


# In[10]:


new_list=my_list+another_list


# In[11]:


new_list


# In list we can immutate/ change the object from the list

# In[12]:


new_list


# In[13]:


new_list[0]='one with caps'


# In[14]:


new_list


# to add an object at the end use append() function

# In[15]:


new_list.append('six')


# In[16]:


new_list


# to remove an object from the list use pop function

# In[17]:


new_list.pop()


# In[18]:


new_list


# In[19]:


popped_item=new_list.pop()


# In[20]:


popped_item


# In[21]:


new_list


# we can not only pop an element from the last but also from any index using indexing

# In[22]:


new_list.pop(0)


# In[23]:


new_list


# sorting of the list

# In[25]:


new_list=['a','e','x','b','c']
num_list=[4,1,8,3]


# In[26]:


new_list.sort()#it does not return anything 


# In[27]:


new_list


# In[28]:


my_sorted_list=new_list.sort()


# In[29]:


my_sorted_list


# In[30]:


#so it does not return anything 

reversing of a list
# In[31]:


new_list.reverse()


# In[32]:


new_list


# In[ ]:




