#!/usr/bin/env python
# coding: utf-8

# In[2]:


1+1


# In[1]:


2+1


# In[2]:


2-1


# In[3]:


2*2


# In[4]:


3/2


# Modulo or "mod" operator

# In[5]:


7/4


# In[6]:


7%4


# In[7]:


50%5


# In[8]:


23%2


# In[9]:


20%2


# power
# 

# In[10]:


2 ** 3


# In[11]:


2 + 10 * 10 +3


# In[12]:


(2+10)*(10+3)


# In[13]:


(10+10)*5


# In[15]:


(10*5)+(100/2)


# In[16]:


0.1+0.2-0.3


# variable assignment
# 

# In[17]:


a=5


# In[18]:


a


# In[19]:


a=10


# In[20]:


a


# In[21]:


a+a


# In[22]:


a


# In[25]:


a=a+a


# In[26]:


a


# doubled the upper part

# 

# using type() function/////

# In[27]:


type(a)


# In[28]:


a=30.1


# In[29]:


type(a)


# In[30]:


my_income = 100
tax_rate=0.1
my_taxes =my_income*tax_rate


# In[31]:


my taxes


# In[32]:


my_taxes


# In[ ]:




